// Code generated by avx512test. DO NOT EDIT.

#include "../../../../../../runtime/textflag.h"

TEXT asmtest_aes_avx512f(SB), NOSPLIT, $0
	VAESDEC X24, X7, X11                               // 62124508ded8 or 6212c508ded8
	VAESENCLAST 7(SI)(DI*1), Z6, Z11                   // 62724d48dd9c3e07000000 or 6272cd48dd9c3e07000000
	RET
